# Generated by Django 6.0.1 on 2026-01-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('target_proficiency', models.FloatField(default=60.0)),
                ('attainment_target', models.FloatField(default=70.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.course')),
            ],
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.programmeoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='po_mappings',
            field=models.ManyToManyField(through='attainment.COPOMapping', to='attainment.programmeoutcome'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField()),
                ('max_marks', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.assessment')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('marks_obtained', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.question')),
            ],
        ),
    ]
