# Generated by Django 6.0.1 on 2026-01-25 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='po_mappings',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='co',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='question',
        ),
        migrations.RenameField(
            model_name='courseoutcome',
            old_name='co_number',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='courseoutcome',
            old_name='target_proficiency',
            new_name='expected_proficiency',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student_id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('CIA', 'CIA'), ('QUIZ', 'Quiz'), ('LAB', 'Lab'), ('PROJECT', 'Project'), ('SEE', 'SEE')], default='CIA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_marks',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attainment.academicyear'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_number', models.CharField(max_length=20)),
                ('max_marks', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.assessment')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='studentmark',
            name='component',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='attainment.assessmentcomponent'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_percentage', models.FloatField()),
                ('attainment_level', models.IntegerField(choices=[(0, 'Not Attained'), (1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attainment.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_percentage', models.FloatField()),
                ('attainment_level', models.IntegerField(choices=[(0, 'Not Attained'), (1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.programoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='COtoPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.programoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.department')),
            ],
        ),
        migrations.AddField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attainment.student'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeacherCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='COPOMapping',
        ),
        migrations.DeleteModel(
            name='ProgrammeOutcome',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
