# Generated by Django 6.0.1 on 2026-01-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0002_academicyear_department_programoutcome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50, unique=True)),
                ('co_target_percentage', models.FloatField(default=60.0, help_text='Percent of students')),
                ('co_student_threshold_percent', models.FloatField(default=60.0)),
                ('attainment_thresholds', models.JSONField(default=dict)),
                ('ia1_weight', models.FloatField(default=20.0)),
                ('ia2_weight', models.FloatField(default=20.0)),
                ('end_sem_weight', models.FloatField(default=60.0)),
                ('direct_weight', models.FloatField(default=0.8)),
                ('indirect_weight', models.FloatField(default=0.2)),
                ('po_target_value', models.FloatField(default=2.5)),
                ('locked', models.BooleanField(default=True, help_text='When True only Admin can change the record')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseoutcome',
            unique_together={('course', 'code')},
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_category',
            field=models.CharField(choices=[('IA1', 'IA-1'), ('IA2', 'IA-2'), ('END', 'End-Semester'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='is_first_year_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='bloom_level',
            field=models.IntegerField(choices=[(1, 'Remember'), (2, 'Understand'), (3, 'Apply'), (4, 'Analyze'), (5, 'Evaluate'), (6, 'Create')], default=2),
        ),
        migrations.AlterField(
            model_name='courseoutcome',
            name='expected_proficiency',
            field=models.FloatField(default=60.0, help_text='percent of marks per student to be considered meeting the CO (e.g., 60%)'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together={('assessment', 'component_number')},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='COFinalAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_percentage', models.FloatField()),
                ('indirect_score', models.FloatField()),
                ('final_value', models.FloatField(help_text='Weighted final CO value (0-100 or 0-3 depending on chosen scale)')),
                ('attainment_level', models.IntegerField(choices=[(0, 'Not Attained'), (1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('course_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='CQIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('hod_reviewed', models.BooleanField(default=False)),
                ('hod_remarks', models.TextField(blank=True, null=True)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_raised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarksUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='marks_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed'), ('IMPORTED', 'Imported')], default='PENDING', max_length=20)),
                ('error_report', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Validation summary, columns, question ids, etc.', null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.assessment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attainment.program'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.academicyear')),
            ],
            options={
                'unique_together': {('academic_year', 'kind')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attainment.semester'),
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('survey_type', models.CharField(choices=[('COURSE', 'Course Exit'), ('PROGRAM', 'Program Exit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='survey_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True, help_text='Survey responses are read-only after upload')),
                ('total_responses', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.surveytemplate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('TEACHER', 'Teacher')], max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attainment.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attainment.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='attainment_target',
        ),
        migrations.CreateModel(
            name='CoursePOAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.course')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.programoutcome')),
            ],
            options={
                'unique_together': {('course', 'program_outcome')},
            },
        ),
        migrations.CreateModel(
            name='ProgramPOAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.program')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.programoutcome')),
            ],
            options={
                'unique_together': {('program', 'program_outcome')},
            },
        ),
        migrations.CreateModel(
            name='SemesterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.semester')),
            ],
            options={
                'unique_together': {('semester',)},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='attainment.surveytemplate')),
            ],
            options={
                'unique_together': {('template', 'code')},
            },
        ),
        migrations.CreateModel(
            name='COIndirectAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirect_score', models.FloatField(help_text='Average score per student (0-3 scale)')),
                ('total_responses', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.courseoutcome')),
                ('survey_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.surveyupload')),
            ],
            options={
                'unique_together': {('course_outcome', 'survey_upload')},
            },
        ),
    ]
