# Generated by Django 4.2.26 on 2026-02-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attainment', '0002_academicyear_department_programoutcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_target_percent', models.FloatField(default=60.0)),
                ('co_target_marks_percent', models.FloatField(default=60.0)),
                ('direct_weightage', models.FloatField(default=0.8)),
                ('indirect_weightage', models.FloatField(default=0.2)),
                ('ia1_weightage', models.FloatField(default=0.2)),
                ('ia2_weightage', models.FloatField(default=0.2)),
                ('end_sem_weightage', models.FloatField(default=0.6)),
                ('po_target_level', models.FloatField(default=2.5)),
                ('level3_threshold', models.FloatField(default=70.0)),
                ('level2_threshold', models.FloatField(default=60.0)),
                ('level1_threshold', models.FloatField(default=50.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSurveyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COURSE', 'Course'), ('PROGRAM', 'Program')], max_length=10)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='direct_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='end_sem_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='ia1_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='ia2_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='indirect_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coattainment',
            name='level',
            field=models.CharField(blank=True, choices=[('LEVEL_0', 'Level 0'), ('LEVEL_1', 'Level 1'), ('LEVEL_2', 'Level 2'), ('LEVEL_3', 'Level 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cotopomapping',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_po_mappings', to='attainment.course'),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='bloom_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='is_first_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='direct_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poattainment',
            name='indirect_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='attainment.assessmentcomponent'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='roll_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('IA1', 'IA 1'), ('IA2', 'IA 2'), ('ENDSEM', 'End Semester'), ('CIA', 'CIA'), ('QUIZ', 'Quiz'), ('LAB', 'Lab'), ('PROJECT', 'Project'), ('SEE', 'SEE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='attainment.course'),
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='attainment.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='attainment.courseoutcome'),
        ),
        migrations.AlterField(
            model_name='coattainment',
            name='attainment_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Attained'), (1, 'Low'), (2, 'Moderate'), (3, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='coattainment',
            name='attainment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coattainment',
            name='course_outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attainment', to='attainment.courseoutcome'),
        ),
        migrations.AlterField(
            model_name='cotopomapping',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_po_mappings', to='attainment.courseoutcome'),
        ),
        migrations.AlterField(
            model_name='cotopomapping',
            name='program_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_po_mappings', to='attainment.programoutcome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attainment.academicyear'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attainment.department'),
        ),
        migrations.AlterField(
            model_name='courseoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='attainment.course'),
        ),
        migrations.AlterField(
            model_name='poattainment',
            name='attainment_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Attained'), (1, 'Low'), (2, 'Moderate'), (3, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='poattainment',
            name='attainment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poattainment',
            name='program_outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attainment', to='attainment.programoutcome'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='attainment.assessmentcomponent'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='marks_obtained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attainment.student'),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='attainment.course'),
        ),
        migrations.AlterField(
            model_name='teachercourseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cotopomapping',
            unique_together={('course_outcome', 'program_outcome')},
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='attainment.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=4)),
                ('is_locked', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='attainment.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('TEACHER', 'Teacher')], max_length=10)),
                ('permission', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='attainment__role_d89474_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='attainment.department')),
            ],
        ),
        migrations.CreateModel(
            name='POSurveyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('program_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='attainment.programoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='MarksUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_uploads', to='attainment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='attainment.globalconfig')),
            ],
        ),
        migrations.CreateModel(
            name='CQIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cqi_actions', to='attainment.courseoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSurveyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_uploads', to='attainment.course')),
            ],
        ),
        migrations.CreateModel(
            name='COSurveyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('course_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='attainment.courseoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attainment.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attainment.semester'),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='attainment.program'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marks_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_marks', to='attainment.marksupload'),
        ),
    ]
