# Generated by Django 4.2.26 on 2026-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0003_globalconfig_alter_courseoutcome_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='allow_student_auto_create',
            field=models.BooleanField(default=True, help_text='If True, unknown RollNos will create Student rows on import'),
        ),
    ]
