# Generated by Django 4.2.26 on 2026-02-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0004_unique_course_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('TEACHER', 'Teacher'), ('PRINCIPAL', 'Principal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('TEACHER', 'Teacher'), ('PRINCIPAL', 'Principal')], default='TEACHER', max_length=10),
        ),
    ]
