# Generated by Django 4.2.26 on 2026-01-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0004_globalconfig_allow_student_auto_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyupload',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attainment.course'),
        ),
        migrations.AddField(
            model_name='surveyupload',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attainment.program'),
        ),
        migrations.CreateModel(
            name='POIndirectAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirect_score', models.FloatField(help_text='Average score per response (0-3 scale)')),
                ('total_responses', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.programoutcome')),
                ('survey_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.surveyupload')),
            ],
            options={
                'unique_together': {('program_outcome', 'survey_upload')},
            },
        ),
    ]
